setup.py - require PyYAML
fixes:
pip install git+https://github.com/open-iscsi/targetd.git
…
ERROR: Could not find a version that satisfies the requirement yaml (from targetd)
ERROR: No matching distribution found for yaml